Last node comparing metric
AISC-understanding-search/maze-transformer pull request #155
Opened 2023-04-06 08:22 UTC by traeuker

This is the first of a few behavioral statistics evaluation metrics. This metric provides insights into emerging capabilities by measuring the proximity of the predicted target to the actual target.

My first PR in a serious git. Let me know if I messed anything up :')

2023-04-06 23:51 UTC, mivanit commented
you should run `make format` and then commit to make sure the linting tests pass. otherwise, this looks good!

2023-04-08 12:43 UTC, luciaquirke commented on maze_transformer/evaluation/path_evals.py
> -        """number of connections in prediction which are are valid paths on the maze"""
doing the lord's work

2023-04-08 12:43 UTC, luciaquirke approved these changes
Nice one!

2023-04-13 22:13 UTC, mivanit requested changes
some minor issues with `corner_jumps`, otherwise LGTM!

2023-04-17 05:24 UTC, mivanit approved these changes

2023-04-20 17:34 UTC, merged